### ISSUE TITLE
plot-orca pip installation fails

### ISSUE THREAD

**Issue by eyalkr1** [kalkairis/COVID19-ISRAEL-public#5]
I added it to requirements-pip.txt (locally), but it fails to install

ERROR: Could not find a version that satisfies the requirement plotly-orca (from -r requirments-pip.txt (line 22)) (from versions: none)
ERROR: No matching distribution found for plotly-orca (from -r requirments-pip.txt (line 22))

**Comment by syagev** [comment]
This is another conda package. From a quick look it simply contains the plotly Python package (installed via `pip install plotly`) and the orca backend, which can be independently downloaded from [here](https://github.com/plotly/orca/releases/download/v1.3.1/windows-release.zip) and installed according to instructions [here](https://github.com/plotly/orca/blob/master/README.md#windows).

Note the two will probably need the right directories to be on the system `PATH` for them to communicate, as per the linked instructions.

**Comment by kalkairis** [comment]
Changed the requirements to have a comment about loading the plotly-orca
